# Generated by Django 5.2.4 on 2025-07-27 22:52

import bookshelf.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_alter_customuser_managers_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', bookshelf.models.CustomUserManager()),
            ],
        ),
    ]
