# Generated by Django 5.2.5 on 2025-08-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='date_posted',
        ),
    ]
